// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using festifact.server.Database;

#nullable disable

namespace festifact.server.Migrations
{
    [DbContext(typeof(FestiFactDbContext))]
    [Migration("20230521203253_DbSeedData")]
    partial class DbSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("festifact.server.Entities.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            CountryOfOrigin = "australia",
                            Description = "A name that evokes a sense of ethereal beauty and natural wonder.",
                            Genre = "pop",
                            Name = "aurora reed"
                        },
                        new
                        {
                            ArtistId = 2,
                            CountryOfOrigin = "mexico",
                            Description = "A name that carries a sense of boldness and adventure.",
                            Genre = "rock",
                            Name = "milo sullivan"
                        },
                        new
                        {
                            ArtistId = 3,
                            CountryOfOrigin = "usa",
                            Description = "A name that exudes elegance and grace.",
                            Genre = "hiphop",
                            Name = "isabella blake"
                        },
                        new
                        {
                            ArtistId = 4,
                            CountryOfOrigin = "netherlands",
                            Description = "A name that conjures images of bold strokes and expressive forms.",
                            Genre = "soul",
                            Name = "jasper graaf"
                        },
                        new
                        {
                            ArtistId = 5,
                            CountryOfOrigin = "portugal",
                            Description = "A name that evokes a sense of enchantment and celestial wonder.",
                            Genre = "rap",
                            Name = "luna martinez"
                        },
                        new
                        {
                            ArtistId = 6,
                            CountryOfOrigin = "ireland",
                            Description = "A name that embodies a sense of versatility and versatility.",
                            Genre = "electronic",
                            Name = "oliver brooks"
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("FestivalId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            FestivalId = 3,
                            NumberOfTickets = 2,
                            ShoppingCartId = 3,
                            TotalAmount = 100m
                        },
                        new
                        {
                            CartItemId = 2,
                            FestivalId = 2,
                            NumberOfTickets = 3,
                            ShoppingCartId = 1,
                            TotalAmount = 45m
                        },
                        new
                        {
                            CartItemId = 3,
                            FestivalId = 4,
                            NumberOfTickets = 1,
                            ShoppingCartId = 2,
                            TotalAmount = 25m
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.Festival", b =>
                {
                    b.Property<int>("FestivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FestivalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FestivalCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FestivalId");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            FestivalId = 1,
                            Age = 21,
                            BannerImageUrl = "/Images/Music/mFestival1.png",
                            Capacity = 200,
                            Date = new DateTime(2023, 6, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Immerse yourself in a harmonious celebration of music at Harmony Music Fest.",
                            FestivalCategoryId = 1,
                            Genre = "pop",
                            Location = "amsterdam",
                            NumberOfDays = 3,
                            Price = 30,
                            ShowId = 2,
                            Title = "harmony music fest"
                        },
                        new
                        {
                            FestivalId = 2,
                            Age = 18,
                            BannerImageUrl = "/Images/Music/mFestival2.png",
                            Capacity = 120,
                            Date = new DateTime(2023, 6, 15, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge your senses in a melodic extravaganza at Melody Mania.",
                            FestivalCategoryId = 1,
                            Genre = "deephouse",
                            Location = "rotterdam",
                            NumberOfDays = 2,
                            Price = 15,
                            ShowId = 3,
                            Title = "melody mania"
                        },
                        new
                        {
                            FestivalId = 3,
                            Age = 22,
                            BannerImageUrl = "/Images/Music/mFestival3.png",
                            Capacity = 180,
                            Date = new DateTime(2023, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready to groove at Rhythm Revival, where the beats come alive and the dance floor ignites.",
                            FestivalCategoryId = 1,
                            Genre = "urban",
                            Location = "utrecht",
                            NumberOfDays = 4,
                            Price = 50,
                            ShowId = 1,
                            Title = "rhythm revival"
                        },
                        new
                        {
                            FestivalId = 4,
                            Age = 21,
                            BannerImageUrl = "/Images/Music/mFestival4.png",
                            Capacity = 250,
                            Date = new DateTime(2023, 8, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for a sonic journey like no other at Sonic Music Summit.",
                            FestivalCategoryId = 1,
                            Genre = "techno",
                            Location = "breda",
                            NumberOfDays = 2,
                            Price = 25,
                            ShowId = 2,
                            Title = "sonic music summit"
                        },
                        new
                        {
                            FestivalId = 5,
                            Age = 18,
                            BannerImageUrl = "/Images/Film/fFestival1.png",
                            Capacity = 150,
                            Date = new DateTime(2023, 6, 10, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore the art and craft of filmmaking, frame by frame, at this captivating film festival.",
                            FestivalCategoryId = 2,
                            Genre = "drama",
                            Location = "eindhoven",
                            NumberOfDays = 2,
                            Price = 15,
                            ShowId = 5,
                            Title = "frame by frame"
                        },
                        new
                        {
                            FestivalId = 6,
                            Age = 8,
                            BannerImageUrl = "/Images/Film/fFestival2.png",
                            Capacity = 500,
                            Date = new DateTime(2023, 7, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Immerse yourself in a dazzling array of cinematic experiences at the Cinematic Kaleidoscope film festival.",
                            FestivalCategoryId = 2,
                            Genre = "comedy",
                            Location = "groningen",
                            NumberOfDays = 5,
                            Price = 12,
                            ShowId = 4,
                            Title = "cinematic kaleidoscope"
                        },
                        new
                        {
                            FestivalId = 7,
                            Age = 18,
                            BannerImageUrl = "/Images/Film/fFestival3.png",
                            Capacity = 300,
                            Date = new DateTime(2023, 8, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Step into a world of cinematic enchantment at the Silver Screen Showcase film festival.",
                            FestivalCategoryId = 2,
                            Genre = "action",
                            Location = "maastricht",
                            NumberOfDays = 3,
                            Price = 18,
                            ShowId = 6,
                            Title = "silver screen showcase"
                        },
                        new
                        {
                            FestivalId = 8,
                            Age = 21,
                            BannerImageUrl = "/Images/Film/fFestival4.png",
                            Capacity = 120,
                            Date = new DateTime(2023, 10, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare to be captivated by the artistry and brilliance of cinema at the Reel Masterpieces film festival.",
                            FestivalCategoryId = 2,
                            Genre = "romance",
                            Location = "hilversum",
                            NumberOfDays = 2,
                            Price = 20,
                            ShowId = 4,
                            Title = "reel masterpieces"
                        },
                        new
                        {
                            FestivalId = 9,
                            Age = 15,
                            BannerImageUrl = "/Images/Dance/dFestival1.png",
                            Capacity = 200,
                            Date = new DateTime(2023, 9, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience the electrifying energy of Rhythm Fusion, where diverse dance styles collide and ignite the stage.",
                            FestivalCategoryId = 3,
                            Genre = "jazz dance",
                            Location = "eindhoven",
                            NumberOfDays = 4,
                            Price = 15,
                            ShowId = 7,
                            Title = "rhythm fusion"
                        },
                        new
                        {
                            FestivalId = 10,
                            Age = 18,
                            BannerImageUrl = "/Images/Dance/dFestival2.png",
                            Capacity = 280,
                            Date = new DateTime(2023, 11, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Embark on a captivating Dance Odyssey, a journey through the rich tapestry of dance from around the world.",
                            FestivalCategoryId = 3,
                            Genre = "hiphop",
                            Location = "haarlem",
                            NumberOfDays = 4,
                            Price = 25,
                            ShowId = 8,
                            Title = "dance odyssey"
                        },
                        new
                        {
                            FestivalId = 11,
                            Age = 21,
                            BannerImageUrl = "/Images/Dance/dFestival3.png",
                            Capacity = 220,
                            Date = new DateTime(2023, 12, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready to groove at the Groove Gala, an explosive celebration of music and dance.",
                            FestivalCategoryId = 3,
                            Genre = "jazz dance",
                            Location = "utrecht",
                            NumberOfDays = 2,
                            Price = 30,
                            ShowId = 7,
                            Title = "groove gala"
                        },
                        new
                        {
                            FestivalId = 12,
                            Age = 22,
                            BannerImageUrl = "/Images/Dance/dFestival4.png",
                            Capacity = 200,
                            Date = new DateTime(2024, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare to be mesmerized by Euphoric Moves, a festival that transcends the boundaries of dance and takes you on a euphoric journey of movement and expression.",
                            FestivalCategoryId = 3,
                            Genre = "latin dance",
                            Location = "amsterdam",
                            NumberOfDays = 2,
                            Price = 35,
                            ShowId = 8,
                            Title = "euphoric moves"
                        },
                        new
                        {
                            FestivalId = 13,
                            Age = 8,
                            BannerImageUrl = "/Images/Literature/lFestival1.png",
                            Capacity = 200,
                            Date = new DateTime(2023, 11, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Step into the enchanting world of storytelling and imagination at the Word Weavers Festival.",
                            FestivalCategoryId = 4,
                            Genre = "fiction",
                            Location = "breda",
                            NumberOfDays = 2,
                            Price = 10,
                            ShowId = 10,
                            Title = "word weavers festival"
                        },
                        new
                        {
                            FestivalId = 14,
                            Age = 8,
                            BannerImageUrl = "/Images/Literature/lFestival2.png",
                            Capacity = 350,
                            Date = new DateTime(2023, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in a fusion of literary voices and ideas at Literary Confluence, a festival that celebrates the diverse landscape of literature.",
                            FestivalCategoryId = 4,
                            Genre = "poetry",
                            Location = "rotterdam",
                            NumberOfDays = 3,
                            Price = 8,
                            ShowId = 9,
                            Title = "literary confluence"
                        },
                        new
                        {
                            FestivalId = 15,
                            Age = 8,
                            BannerImageUrl = "/Images/Literature/lFestival3.png",
                            Capacity = 180,
                            Date = new DateTime(2023, 10, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enter a realm of literary delights at the Bookish Delights festival, where books come alive and reading is celebrated with fervor.",
                            FestivalCategoryId = 4,
                            Genre = "thriller",
                            Location = "groningen",
                            NumberOfDays = 2,
                            Price = 15,
                            ShowId = 10,
                            Title = "bookish delights"
                        },
                        new
                        {
                            FestivalId = 16,
                            Age = 8,
                            BannerImageUrl = "/Images/Literature/lFestival4.png",
                            Capacity = 250,
                            Date = new DateTime(2024, 2, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience the rich tapestry of literature at the Literary Mosaic festival, where diverse voices and genres come together to create a vibrant literary landscape.",
                            FestivalCategoryId = 4,
                            Genre = "non fiction",
                            Location = "maastricht",
                            NumberOfDays = 2,
                            Price = 12,
                            ShowId = 9,
                            Title = "literary mosaic"
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.FestivalCategory", b =>
                {
                    b.Property<int>("FestivalCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FestivalCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FestivalCategoryId");

                    b.ToTable("FestivalCategories");

                    b.HasData(
                        new
                        {
                            FestivalCategoryId = 1,
                            Name = "music festival"
                        },
                        new
                        {
                            FestivalCategoryId = 2,
                            Name = "film festival"
                        },
                        new
                        {
                            FestivalCategoryId = 3,
                            Name = "dance festival"
                        },
                        new
                        {
                            FestivalCategoryId = 4,
                            Name = "literature festival"
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfPublication")
                        .HasColumnType("int");

                    b.HasKey("FilmId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CountryOfOrigin = "australia",
                            Description = "A haunting psychological thriller that delves into the depths of the human psyche.",
                            Director = "olivia taylor",
                            Title = "whispers in the dark",
                            YearOfPublication = 1996
                        },
                        new
                        {
                            FilmId = 2,
                            CountryOfOrigin = "canada",
                            Description = "In the atmospheric thriller Shadows of Destiny,\" shadows hold secrets and darkness conceals the truth.",
                            Director = "samuel wright",
                            Title = "shadows of destiny",
                            YearOfPublication = 2011
                        },
                        new
                        {
                            FilmId = 3,
                            CountryOfOrigin = "usa",
                            Description = "Fragments of Time pieces together fragmented memories, intersecting timelines, and the threads of destiny.",
                            Director = "isabella lee",
                            Title = "fragments of time",
                            YearOfPublication = 2016
                        },
                        new
                        {
                            FilmId = 4,
                            CountryOfOrigin = "ireland",
                            Description = "Embark on a profound and introspective Journey of the Soul.",
                            Director = "ethan anderson",
                            Title = "journey of the soul",
                            YearOfPublication = 2012
                        },
                        new
                        {
                            FilmId = 5,
                            CountryOfOrigin = "england",
                            Description = "A captivating romantic drama that explores the transformative power of love and the delicate nature of human connections.",
                            Director = "benjamin martinez",
                            Title = "lost in reverie",
                            YearOfPublication = 2020
                        },
                        new
                        {
                            FilmId = 6,
                            CountryOfOrigin = "usa",
                            Description = "Echoes of Yesterday takes audiences on a nostalgic journey through time.",
                            Director = "ava williams",
                            Title = "echoes of yesterday",
                            YearOfPublication = 2008
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            ShoppingCartId = 1,
                            VisitorId = 2
                        },
                        new
                        {
                            ShoppingCartId = 2,
                            VisitorId = 3
                        },
                        new
                        {
                            ShoppingCartId = 3,
                            VisitorId = 1
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShowId");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            ShowId = 1,
                            ArtistId = 2,
                            Description = "Get ready for an explosive showcase of music as top artists take the main stage by storm. Experience an unforgettable night filled with electrifying performances and high-energy entertainment.",
                            EndTime = new DateTime(2023, 7, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/mFestivalShow1.png",
                            StartTime = new DateTime(2023, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "main stage madness"
                        },
                        new
                        {
                            ShowId = 2,
                            ArtistId = 1,
                            Description = "Immerse yourself in the soothing melodies of acoustic music. Sit back, relax, and let the enchanting sounds of talented singer-songwriters create an atmosphere of pure bliss and heartfelt emotions.",
                            EndTime = new DateTime(2023, 6, 2, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/mFestivalShow2.png",
                            StartTime = new DateTime(2023, 6, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "acoustic bliss"
                        },
                        new
                        {
                            ShowId = 3,
                            ArtistId = 3,
                            Description = "Unleash your inner rock enthusiast and witness the raw power of live rock music.",
                            EndTime = new DateTime(2023, 6, 15, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/mFestivalShow3.png",
                            StartTime = new DateTime(2023, 6, 15, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "rock revolution"
                        },
                        new
                        {
                            ShowId = 4,
                            ArtistId = 0,
                            Description = "Join us for a glamorous evening as we kick off the film festival in style.",
                            EndTime = new DateTime(2023, 7, 19, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 3,
                            ImageUrl = "/Images/Shows/fFestivalShow1.png",
                            StartTime = new DateTime(2023, 7, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "opening night spectacular"
                        },
                        new
                        {
                            ShowId = 5,
                            ArtistId = 0,
                            Description = "Step back in time and relish the golden era of cinema with a showcase of timeless classics.",
                            EndTime = new DateTime(2023, 6, 10, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2,
                            ImageUrl = "/Images/Shows/fFestivalShow2.png",
                            StartTime = new DateTime(2023, 6, 10, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "classic cinema showcase"
                        },
                        new
                        {
                            ShowId = 6,
                            ArtistId = 0,
                            Description = "Celebrate the creativity and innovation of independent filmmaking with a showcase of captivating indie gems.",
                            EndTime = new DateTime(2023, 8, 25, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            ImageUrl = "/Images/Shows/fFestivalShow3.png",
                            StartTime = new DateTime(2023, 8, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "indie gems gala"
                        },
                        new
                        {
                            ShowId = 7,
                            ArtistId = 4,
                            Description = "Immerse yourself in a dazzling display of dance styles and mesmerizing choreography.",
                            EndTime = new DateTime(2023, 9, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/dFestivalShow1.png",
                            StartTime = new DateTime(2023, 9, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "dance extravaganza"
                        },
                        new
                        {
                            ShowId = 8,
                            ArtistId = 5,
                            Description = "Witness the raw energy and fierce competition of street dance as crews battle it out in an electrifying showdown.",
                            EndTime = new DateTime(2023, 11, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/dFestivalShow2.png",
                            StartTime = new DateTime(2023, 11, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "street dance showdown"
                        },
                        new
                        {
                            ShowId = 9,
                            ArtistId = 0,
                            Description = "Step into the world of renowned authors as they take the stage to share insights into their works. Engage in fascinating discussions, hear captivating readings, and get a glimpse into the creative minds behind some of the most celebrated literary works.",
                            EndTime = new DateTime(2023, 12, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/lFestivalShow1.png",
                            StartTime = new DateTime(2023, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "author spotlight"
                        },
                        new
                        {
                            ShowId = 10,
                            ArtistId = 0,
                            Description = "Join a vibrant book club discussion brought to life on stage.",
                            EndTime = new DateTime(2023, 11, 8, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 0,
                            ImageUrl = "/Images/Shows/lFestivalShow2.png",
                            StartTime = new DateTime(2023, 11, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "book club live"
                        });
                });

            modelBuilder.Entity("festifact.server.Entities.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Residence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            VisitorId = 1,
                            DateOfBirth = new DateTime(1980, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@avans.nl",
                            Firstname = "paul",
                            Lastname = "hertog",
                            Password = 1234,
                            Residence = "breda",
                            Sex = "male"
                        },
                        new
                        {
                            VisitorId = 2,
                            DateOfBirth = new DateTime(1979, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hans@avans.nl",
                            Firstname = "hans",
                            Lastname = "graaf",
                            Password = 34,
                            Residence = "breda",
                            Sex = "male"
                        },
                        new
                        {
                            VisitorId = 3,
                            DateOfBirth = new DateTime(1950, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tom@avans.nl",
                            Firstname = "tom",
                            Lastname = "koning",
                            Password = 1211,
                            Residence = "scheveningen",
                            Sex = "male"
                        },
                        new
                        {
                            VisitorId = 4,
                            DateOfBirth = new DateTime(2002, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linda@avans.nl",
                            Firstname = "linda",
                            Lastname = "koningin",
                            Password = 188,
                            Residence = "amsterdam",
                            Sex = "female"
                        },
                        new
                        {
                            VisitorId = 5,
                            DateOfBirth = new DateTime(1992, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lieke@avans.nl",
                            Firstname = "lieke",
                            Lastname = "gravin",
                            Password = 4591,
                            Residence = "eindhoven",
                            Sex = "female"
                        },
                        new
                        {
                            VisitorId = 6,
                            DateOfBirth = new DateTime(1995, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roy@avans.nl",
                            Firstname = "roy",
                            Lastname = "baron",
                            Password = 12399,
                            Residence = "rotterdam",
                            Sex = "male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
